[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1043d9b50>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e54cedbf-f2a4-4c6b-a37b-0478ca039b88
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1043d9d60>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e54cedbf-f2a4-4c6b-a37b-0478ca039b88
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1043daf90>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e54cedbf-f2a4-4c6b-a37b-0478ca039b88