[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ab49b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a729b004-c421-403c-836b-43095f8f11e8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ab4740>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a729b004-c421-403c-836b-43095f8f11e8
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ab7f80>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a729b004-c421-403c-836b-43095f8f11e8