[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1043f19d0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a1f9e272-951d-49ed-afb5-3fa137eefd3a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1043f33b0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a1f9e272-951d-49ed-afb5-3fa137eefd3a
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x1043f1be0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/a1f9e272-951d-49ed-afb5-3fa137eefd3a