[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104e74ce0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/933ba925-9f61-415a-b96f-afd0b9c25f70
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104e75880>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/933ba925-9f61-415a-b96f-afd0b9c25f70
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x104cbf920>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/933ba925-9f61-415a-b96f-afd0b9c25f70