[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ac1190>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e0606e6c-95d7-420b-8376-2334002627f2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102913bf0>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e0606e6c-95d7-420b-8376-2334002627f2
[33mWARNING [0m urllib3.connectionpool:connectionpool.py:870 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x102ac1f10>: Failed to establish a new connection: [Errno 61] Connection refused')': /session/e0606e6c-95d7-420b-8376-2334002627f2